# Generated by Django 5.2.3 on 2025-06-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
