# Generated by Django 5.2.3 on 2025-06-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeterinaryHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('location_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
