# Generated by Django 5.2.3 on 2025-06-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_veterinaryhospital_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
        ),
    ]
