# Generated by Django 5.2.3 on 2025-06-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_animal_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaryhospital',
            name='image',
            field=models.ImageField(default='', upload_to='main_app/static/uploads'),
        ),
    ]
